"""add_domain_id_to_companies

Revision ID: cda24d6f66d4
Revises: 403e31e14180
Create Date: 2026-03-13 02:31:48.346058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda24d6f66d4'
down_revision: Union[str, None] = '403e31e14180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('domain_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_domain_id'), 'companies', ['domain_id'], unique=False)
    op.create_unique_constraint('uq_company_name_domain', 'companies', ['name', 'domain_id'])
    op.create_foreign_key(None, 'companies', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint('uq_company_name_domain', 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_domain_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_column('companies', 'domain_id')
    # ### end Alembic commands ###
